
pt = 1.0712E+00/1013.25;
ps = 3.8885E-04/1013.25;

band = 740;

ii=1;
[duration_self(ii),duration_for(ii),...
 beta_self(ii),beta_for(ii),b2s(ii),b2f(ii)] = ...
  co2_param_AIRS2002(band,pt,ps);

ii=2;
[duration_self(ii),duration_for(ii),...
  beta_self(ii),beta_for(ii),b2s(ii),b2f(ii)] = ...
  co2_param_JULY20_2002(band,pt,ps);

ii=3;
[duration_self(ii),duration_for(ii),...
  beta_self(ii),beta_for(ii),b2s(ii),b2f(ii)] = ...
  co2_param_JJOHNS2002(band,pt,ps,1);

ii=4;
[duration_self(ii),duration_for(ii),...
  beta_self(ii),beta_for(ii),b2s(ii),b2f(ii)] = ...
  co2_param_JJOHNS2002_JULY3(band,pt,ps);

ii=5;
[duration_self(ii),duration_for(ii),...
  beta_self(ii),beta_for(ii),b2s(ii),b2f(ii)] = ...
  co2_param_JJOHNS2002_ORIG(band,pt,ps);